myStr="Harry is a good boy"
print(myStr)
print(myStr[4])
print(myStr[0:4]) #here 0 i sincluding & 4 is excluding
print(myStr[0:5])
print(len(myStr))
print(myStr[0:19])
#print(myStr[18])
#print(myStr[78])
print(myStr[0:78])
print(myStr[0:5:2])
print(myStr[:5])
print(myStr[0:])
print(myStr[:])
print(myStr[ : : ])
print(myStr[0:19:1])
print(myStr[::1])
print(myStr[0::1])
print(myStr[:19:1])
print(myStr[::2])
print(myStr[::3])
print(myStr[::9])
print(myStr[::5559])
#print(myStr[-1:0])
print(myStr[15:1])
print(myStr[-4:-2])
print(myStr[15:17])
print(myStr[: :-1])
print(myStr[: :-2])
print(myStr.isalpha())
print(myStr.isalnum())
"""myStr="Harryisagoodboy"
print(myStr.isalnum())"""
print(myStr.endswith("boy"))
print(myStr.endswith("asf"))
print(myStr.count("b"))
print(myStr.count("o"))
print(myStr.capitalize())
print(myStr.lower())
print(myStr.find("is"))
print(myStr.replace("is","are"))