# files = open("harry.txt","a")
files = open("harry.txt", "r+")
# content = files.read()
# content=files.readline()
content=files.write("Harry is great in the world\n more line\n one more line ")
# content=files.readlines()
#print(content)
# print(files.tell())
# content=files.readlines()
# content=files.tell()
# print(content)

print(files.readlines())
# files.seek(10)
files.seek(9)
print("where you want to read start the files after seeking\n\n")
print(files.readlines())
te
files.close()